### ISSUE TITLE
BUG maxscore.sampler.maxhelp not playin

### ISSUE THREAD

**Issue by gregbeller** [HfMT-ZM4/MaxScore#250]
Hi Georg,

so after:
* a clean install of MaxScore (Version 2.5.7 for Max 8.6 (and higher) and Ableton Live Suite 11 (and higher) – posted on May 09, 2024) 
* loading from maxscore overview maxscore.sampler.maxhelp
* I get the following errors when trying to load default banks:

pattrforward: (bank): could not resolve requested object (parent::parent::GUI::editor::bank)
pattrforward: (bank): could not resolve requested object (parent::parent::GUI::editor::bank)
pattrforward: (u855002626[1]): could not resolve requested object (parent::parent::parent::maxscore.sampler.menus::-51-instrument::setchannels)
pattrforward: (u855002626): could not resolve requested object (parent::parent::parent::maxscore.sampler.menus::-51-instrument::setinstrument)

Consequence is that I can not get any sound out of Maxscore.sampler.

Please fix as soon as possible for the HSS project...

Best

**Comment by computermusik** [comment]
Oh, that’s strange. I don’t have this issue on my computer. Can I have a Zoom session with you so I can have a look at your configuration?BTW, the DJster issue is harmless and due to two objects not initializing at the very same time. I‘ll remove the issue though so that users aren’t misled to believe that this is a bug.On 11. May 2024, at 12:02, gregbeller ***@***.***> wrote:﻿
Hi Georg,
so after:

a clean install of MaxScore (Version 2.5.7 for Max 8.6 (and higher) and Ableton Live Suite 11 (and higher) – posted on May 09, 2024)
loading from maxscore overview maxscore.sampler.maxhelp
I get the following errors when trying to load default banks:

pattrforward: (bank): could not resolve requested object (parent::parent::GUI::editor::bank)
pattrforward: (bank): could not resolve requested object (parent::parent::GUI::editor::bank)
pattrforward: (u855002626[1]): could not resolve requested object (parent::parent::parent::maxscore.sampler.menus::-51-instrument::setchannels)
pattrforward: (u855002626): could not resolve requested object (parent::parent::parent::maxscore.sampler.menus::-51-instrument::setinstrument)
Consequence is that I can not get any sound out of Maxscore.sampler.
Please fix as soon as possible for the HSS project...
Best

**Comment by computermusik** [comment]
I'm wondering whether your message had the wrong format: instrument Bell-2.instr 2 3 -50. I suspect that you copied this message from the help file 

<img width="312" alt="image" src="https://github.com/HfMT-ZM4/MaxScore/assets/17442406/502c48f1-8fe0-458b-a115-c3172ebbc3b6">

and may have deleted the "1" at the end. If the message has five list items and -50 is the last number it is treated as a channel number. If the list has six items and the second to last is -50 and the last 1, this message sets panorama to left on channel 1. In short, the last number is always the channel number, whether or not the channels and panorama is specified. if it's -50 than the sampler will attempt to set it values on a channel that doesn't exist. Hence the error messages.

I will clip channel numbers to 1 and 32 in the next iteration of the sampler.
